added docstring for text preprocess function
UBC-MDS/text_processing_util_mds24 pull request #3
Opened 2024-01-10 00:00 UTC by allan8392

2024-01-10 02:22 UTC, MoNorouzi23 commented
thanks Allen. It has just one typo!

2024-01-11 22:52 UTC, jy1909 requested changes
Adding output to example.

2024-01-11 22:52 UTC, jy1909 commented on src/text_processing_util_mds24/text_processing_util_mds24.py
> +                    "we are the best"])
```suggestion
    >>> text_clean(["We are group 10.",
                    "We are the best!"])
    ["we are group", "we are the best"]
```

2024-01-11 22:53 UTC, jy1909 approved these changes

2024-01-11 22:53 UTC, merged